name: date_picker_timeline
description: Flutter Date Picker Library that provides a calendar as a horizontal timeline.
version: 1.2.7
homepage: https://github.com/iamvivekkaushik/DatePickerTimelineFlutter

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  yaml:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec